name: Build, Test, and Publish Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# We need permissions to push to the container registry:
permissions:
  contents: read
  packages: write

jobs:
  build-test-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go-version:
          - "1.22"
          - "1.23"
        include:
          - os: ubuntu-latest
            urlTemplate: "https://github.com/caddyserver/xcaddy/releases/download/{{version}}/xcaddy_{{rawVersion}}_linux_amd64.tar.gz"
            name: "xcaddy"
            pathInArchive: "xcaddy"

          - os: "macos-latest"
            urlTemplate: "https://github.com/caddyserver/xcaddy/releases/download/{{version}}/xcaddy_{{rawVersion}}_mac_amd64.tar.gz"
            name: "xcaddy"
            pathInArchive: "xcaddy"

          - os: "windows-latest"
            urlTemplate: "https://github.com/caddyserver/xcaddy/releases/download/{{version}}/xcaddy_{{rawVersion}}_windows_amd64.zip"
            name: "xcaddy.exe"
            pathInArchive: "xcaddy.exe"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          cache: true
          go-version: ${{ matrix.go-version }}

      - name: Set up xcaddy
        uses: engineerd/configurator@v0.0.10
        with:
          name: ${{ matrix.name }}
          pathInArchive: ${{ matrix.pathInArchive }}
          fromGitHubReleases: "true"
          repo: "caddyserver/xcaddy"
          version: "latest"
          urlTemplate: ${{ matrix.urlTemplate }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          xcaddy build master --output ${{ runner.temp }}/${{ matrix.name }} --with github.com/mholt/caddy-l4=./
          echo ''
          echo '########'
          echo "# ${{ runner.temp }}/${{ matrix.name }} version"
          ${{ runner.temp }}/${{ matrix.name }} version
          echo '########'
          echo ''
          echo '########'
          echo "# ${{ runner.temp }}/${{ matrix.name }} list-modules"
          ${{ runner.temp }}/${{ matrix.name }} list-modules
          echo '########'
          echo ''
          echo '########'
          echo "# ${{ runner.temp }}/${{ matrix.name }} build-info"
          ${{ runner.temp }}/${{ matrix.name }} build-info
          echo '########'

      - name: Test
        run: |
          go test -v ./...

  # This job only runs on ubuntu-latest and only if we're on "master" (so it doesn't
  # try to push images from PRs or from Windows/macOS builds).
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          # Adjust the tag to your own naming convention if desired
          tags: ghcr.io/erbesharat/caddy-l4:latest
